Manager/urls.py
from django.urls import path
from . import views

app_name = "manager"

urlpatterns = [
    path('', views.OrderList.as_view(), name ="admin"),
    path('menu/', views.MenuState.as_view(), name ="menu"),

]

Menu/urls.py
from django.urls import path
from . import views

app_name = "menu"

urlpatterns = [

    path("state/update/",views.MenuStateUpdate,name = "state_update"),

]

Order/urls.py
from django.urls import path
from . import views

app_name = "order"

urlpatterns = [
    path('search/',views.OrderSearch.as_view(),name = "search"),
    path("state/update/",views.OrderStateUpdate,name = "state_update"),
    path("create/",views.OrderCreate,name = "create"),
]

Skkur/urls.py
from django.urls import path
from . import views

app_name = "skkur"

urlpatterns = [
    path('', views.MenuList.as_view(), name = "index"),
    path('cart/', views.Cart.as_view(), name = "cart"),
    path('complete/', views.Complete.as_view(), name = "complete"),
    path('order_complete/', views.OrderComplete.as_view(), name = "order_complete")
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    #path('admin/', admin.site.urls),
    path('',include("Skkur.urls")),
    path('order/',include("Order.urls")),
    path('admin/',include("Manager.urls")),
    path('menu/',include("Menu.urls")),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Manager/models.py
from django.db import models

# Create your models here.

Menu/models.py
from django.db import models

class Mode(models.Model):
    name = models.CharField(max_length = 100)

# Create your models here.
class Menu(models.Model):
    STATUS_CHOICES = (
        ('true', '주문가능'),
        ('false', '품절'),
    )
    mode = models.ManyToManyField(Mode)
    name = models.CharField(max_length = 100)
    image = models.ImageField(null = True, upload_to = "menu")
    price = models.IntegerField()
    status = models.CharField(max_length = 100, choices = STATUS_CHOICES)

Order/models.py
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField

class Order(models.Model):
    STATUS_CHOICES = (
        ('checking', 'checking'),
        ('in_progress', 'in_progress'),
        ('done', 'done'),
    )
    table_num = models.IntegerField()
    total_price = models.IntegerField()
    created_at = models.DateTimeField(auto_now_add = True)
    status = models.CharField(max_length = 100, choices = STATUS_CHOICES)
    phone_num = PhoneNumberField()

class Ordered_Menu(models.Model):
    menu = models.ForeignKey("Menu.Menu",on_delete = models.CASCADE)
    order = models.ForeignKey(Order,on_delete = models.CASCADE)
    quantity = models.IntegerField()

    def get_menu_name(self):
        print("model : ",self.menu.name)
        return self.menu.name

Skkur/models.py
from django.db import models

# Create your models here.

Manager/views.py
from django.shortcuts import render
from Order.utils import Orders_to_Json
from django.views.generic import View, ListView

from Order.models import Order
from Menu.models import Menu

from .utils import Menues_to_Json

class OrderList(ListView):
    template_name = "admin/admin.html"
    model = Order

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        queryset = self.get_queryset()
        context["queryset_json"] = Orders_to_Json(queryset)

        return context

class MenuState(ListView):
    template_name = "admin/menu.html"
    model = Menu

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        queryset = self.get_queryset().filter(mode = "2")
        context["menu_list"] = Menues_to_Json(queryset)

        return context

Menu/views.py
from django.shortcuts import render
from django.views.generic import View
from django.views.decorators.csrf import csrf_exempt

from django.http import JsonResponse
import json

from .models import Menu

def MenuStateUpdate(request):
        if request.method == "POST":
            data = json.loads(request.body)
            order = Menu.objects.get(id = data["id"])
            print(order.status)
            if order.status == "true":
                order.status = "false"
                order.save()
            else:
                order.status = "true"
                order.save()


            return JsonResponse({'success': True})

Order/views.py
from django.shortcuts import render
from django.views.generic import View, ListView
from .utils import Orders_to_Json
import json
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt

from .models import Order, Ordered_Menu
from Menu.models import Menu


def OrderStateUpdate(request):
        if request.method == "POST":
            data = json.loads(request.body)
            order = Order.objects.get(id = data["id"])
            order.status = data["state"]
            order.save()

            return JsonResponse({'success': True})


class OrderSearch(ListView):
    template_name = "order/search.html"
    model = Order

    def get_context_data(self, **kwargs):
        context = {}
        queryset = self.get_queryset()
        context["data"] = Orders_to_Json(queryset)

        return context

    def get(self, request, *args, **kwargs):
        if request.META.get('HTTP_X_REQUESTED_WITH') == 'XMLHttpRequest':
            data = self.get_context_data()
            return JsonResponse(data)
        else:
            return super().get(request, *args, **kwargs)



def OrderCreate(request):
    if request.method == "POST":
        data = json.loads(request.body)

        print(data)
        menues = json.loads(data[0]["menus"])
        print(menues)
        total_price = 0
        order = Order()
        order.table_num = data[0]["table_num"]
        order.total_price = 0

        order.status = "checking"
        order.phone_num = data[0]["phone_num"]
        order.save()
        for menu in menues:
            new = Ordered_Menu()
            new.menu = Menu.objects.get(name = menu["name"])
            print(new.menu)
            new.quantity = menu["amount"]
            new.order = order
            new.save()
            price = Menu.objects.get(name = menu["name"]).price
            total_price += price * int(menu["amount"])

        order.total_price = total_price
        order.save()

        return JsonResponse({'success': True})

Skkur/views.py
from django.views.generic import ListView, View, TemplateView
import json

from Menu.models import Menu


class MenuList(ListView):
    template_name = "index.html"
    model = Menu

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context["menu_list"] = Menu.objects.filter(mode = "2",status = "true")
        return context

class Cart(TemplateView):
     template_name = 'cart.html'

class OrderComplete(TemplateView):
     template_name = 'order_complete.html'

class Complete(TemplateView):
     template_name = 'complete.html'

templates/cart.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'css/cart.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/index.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <title>skrrrr.exe</title>
</head>
<body>
    <div class="background" style="
    display: grid;
    grid-template-rows: 50% 50%;">
        <div class="menu_wrap">
            
        </div>
        <div class="cart_order">
            <div class="order_info">
                total <p id="total_price" style="padding-left: 10px; padding-right: 10px;">0</p>
            </div>
            <div class="order_info">
                table <br> number <input id="table_number" type="text">
            </div>     
            <div class="order_info">
                phone <br> number <input id="phone_number" type="text">
            </div>
            <input type="checkbox" checked id="check_box"> 개인정보 수집에 동의합니다.
            <button type="button" class="order_button" onclick="order_request()">주문하기</button>
            <button class="back_button" onclick="back()">돌아가기</button>
        </div>
    </div>

    <!-- amount validation modal -->
    <div id="order_alert" class="modal">
        <div class="modal_contents">
            <button target="order_alert" class="modal_close" onclick="modal_close(this)"></button>
            <div class="modal_text">
                총 금액이 클립보드에 복사 되었습니다. <br>
                정말 주문 하시겠습니까? <br>
                취소할 수 없습니다.
            </div>
            <button class="order_yes" onclick="order_yes()"></button>
            <button class="order_no" onclick="order_no()"></button>
        </div>
    </div>

</body>
<script type="text/javascript" src="{% static 'js/cart.js' %}"></script>
</html>

templates/complete.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
    <link rel="stylesheet" type="text/css" href="{% static 'css/index.css' %}">
    <title>skrrrr.exe</title>
</head>
<body>
    <div class="background">
        <div class="menu_wrap" style="font-family: 'Press Start 2P'; flex-direction: column; justify-content: flex-start; align-content: center; align-items: center; padding-left: 0;">
            <img src="{% static 'img/very_good.png' %}" style="width: 218px; height: 225px;" alt="">
            <h1 style="color: #353394">15</h1>
            <button class="complete_button_" onclick="location.replace('/order/search/')">주문 내역 검색</button>
            <button class="complete_button_" onclick="location.replace('/')">더 주문하러 가기</button>
        </div>
    </div>

</body>
<script type="text/javascript" src="{% static 'js/index.js' %}"></script>
</html>

templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
    <link rel="stylesheet" type="text/css" href="{% static 'css/index.css' %}">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <title>skrrrr.exe</title>
</head>
<body>
    <div class="background" style="
    display: grid;
    grid-template-rows: 20% 60% 40%;">
        <div id = "button_area">
            <button id="search_button" class="add_button" onclick="location.href = '{% url 'order:search' %}'">주문내역 검색</button>
        </div>
        <div class="menu_wrap_index">

            {% for menu in menu_list %}
                <div id="{{menu.id}}" class="menu">
                    <div class="picture">
                        {% if menu.image %}
                            <img src="{{menu.image.url}}" alt="">
                        {% endif %}
                    </div>
                    <div class="option">
                        <div class="name box">{{menu.name}}</div>
                        <div class="able box">{{menu.get_status_display}}</div>
                        <div class="price box">{{menu.price}}</div>
                        <div class="pack">
                            <div class="amount box">
                                <button id="{{menu.id}}" class="down" onclick="down(this)"></button> 
                                <p id="{{menu.id}}_amount">1</p>
                                <button id= "{{menu.id}}"class="up" style="float: right;" onclick="up(this)"></button>
                            </div>
                            <button id="{{menu.id}}" class="add_button" onclick="add(this)">담기</button>
                        </div>    
                    </div>
                </div>
            {% endfor %}

        </div>
        <div class="order">
            <p id="order_count">0</p>
            <button class="order_button" onclick="make_order()">장바구니</button>
        </div>
    </div>

    <!-- amount validation modal -->
    <div id="order_alert" class="modal">
        <div class="modal_contents">
            <button target="order_alert" class="modal_close" onclick="modal_close(this)"></button>
            <div class="modal_text">
                1개 이상 주문해 주세요.
            </div>
            <button target="order_alert" class="modal_ok" onclick="modal_close(this)"></button>
        </div>
    </div>

     <!-- added product modal -->
     <div id="add_alert" class="modal">
        <div class="modal_contents">
            <button target="add_alert" class="modal_close" onclick="modal_close(this)"></button>
            <div class="modal_text">
                ####
            </div>
            <button target="add_alert" class="modal_ok" onclick="modal_close(this)"></button>
        </div>
    </div>

    <!-- cart alret modal -->
    <div id="cart_alert" class="modal">
        <div class="modal_contents">
            <button target="cart_alert" class="modal_close" onclick="modal_close(this)"></button>
            <div class="modal_text" style="display:flex;justify-content: center;align-items: center;">
                <img src="{% static 'img/error.jpg' %}" alt="" style="width:40px; height: 40px;"> 장바구니에 담은 내역이 없습니다.
            </div>
            <button target="cart_alert" class="modal_ok" onclick="modal_close(this)"></button>
        </div>
    </div>
    <form id = "cart_form" method = "post" action = "{% url 'skkur:cart' %}">{% csrf_token %}</form>
</body>
<script type="text/javascript" src="{% static 'js/index.js' %}"></script>
</html>

templates/order/search.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1, user-scalable=no"/>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Press+Start+2P&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/order/style.css' %}" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <title>주문 내역 검색 페이지</title>
</head>
<body>
    <div class="page">
        <div class="background"></div>
        <div class="content">
            <div class="content-header">
                <div class="title">주문 내역 검색</div>
                <hr id="separation">
                <div class="search-wrap">
                    <input id="search-input" placeholder="전화번호로 검색하기">
                    <button id="search-button">search</button>
                    <button id="home-button" onclick = "location.href = '{% url 'order:search' %}'">🏠</button>

                </div>
            </div>
            <div class="order-list">
                <div class="order-container"></div>
            </div>
        </div>
    </div>
    <script type = "text/javascript">const data = {{data|safe}};</script>
    <script type="text/javascript" src="{% static 'js/order/search.js' %}"></script>
</body>
</html>

templates/order_complete.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
    <link rel="stylesheet" type="text/css" href="{% static 'css/index.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <title>skrrrr.exe</title>
</head>
<body>
    <div class="background">
        <div class="menu_wrap" style="font-family: 'Press Start 2P'; flex-direction: column; padding-left: 0;">
            <div class="complete_total">total <div id = "total_price" class="box" style="width:200px"></div></div>
            <div style="margin: 50px auto 0px auto;">
                카카오뱅크 <br>

                7979-79-88793 <br>
                (이은지)
            <div>
            <div class="complete_pop">
                <div class="message" style="margin-top: 50px; font-size: 14px; margin-bottom: 15px;">
                    위 금액을 송금 완료 하셨나요?
                </div>
                <button class="complete_button" onclick="pay_yes();">계좌이체 완료❤️</button>
                <button class="complete_button" onclick="pay_no();">주문 안 할게요</button>
            </div>
        </div>
    </div>

</body>
<script type = "text/javascript">const csrftoken = "{{csrf_token}}"</script>
<script type="text/javascript" src="{% static 'js/complete.js' %}"></script>
</html>